[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "nyef pokhara"
authors = [{name = "Krishesh Shrestha", email = "info@krisheshshrestha.com.np"}]
dynamic = ["version", "description"]
